import assert from "node:assert/strict";
import { chmod, cp, lstat, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

const root = import.meta.dirname;

test("component identity survives repacking/pruning and rejects corrupted or symlinked snapshots", { skip: process.platform !== "darwin" }, async (t) => {
	const workspace = await mkdtemp(join(tmpdir(), "browser-components-"));
	t.after(() => rm(workspace, { recursive: true, force: true }));
	const home = join(workspace, "home");
	await mkdir(join(home, "Library", "Application Support"), { recursive: true });
	const releaseA = join(workspace, "release-a"), releaseB = join(workspace, "release-b");
	await mkdir(releaseA);
	await cp(join(root, "chrome-extension"), join(releaseA, "chrome-extension"), { recursive: true });
	for (const name of ["native-host.mjs", "install-chrome-relay.mjs"]) await cp(join(root, name), join(releaseA, name));
	await cp(releaseA, releaseB, { recursive: true });
	const run = (release, operation, targetHome = home) => spawnSync(process.execPath, [join(release, "install-chrome-relay.mjs"), operation], { env: { HOME: targetHome }, encoding: "utf8", timeout: 10_000 });
	const installed = run(releaseA, "install"); assert.equal(installed.status, 0, installed.stderr);
	const first = JSON.parse(installed.stdout);
	const firstBytes = await readFile(join(first.extensionDir, "service-worker.js"));
	const firstInfo = await lstat(join(first.extensionDir, "service-worker.js"));
	const launcher = await readFile(first.launcherPath, "utf8");
	assert.ok(!launcher.includes(releaseA)); assert.ok(!launcher.includes(root));
	await rm(releaseA, { recursive: true });
	await writeFile(join(releaseB, "index.ts"), "// unrelated product command update\n");
	let status = JSON.parse(run(releaseB, "status").stdout);
	assert.equal(status.installed, true); assert.equal(status.componentState, "ready");
	assert.equal(status.extensionDir, first.extensionDir);
	assert.equal(run(releaseB, "install").status, 0);
	assert.equal((await lstat(join(first.extensionDir, "service-worker.js"))).mtimeMs, firstInfo.mtimeMs);
	await chmod(join(first.extensionDir, "service-worker.js"), 0o644);
	assert.equal(JSON.parse(run(releaseB, "status").stdout).componentState, "invalid");
	assert.notEqual(run(releaseB, "install").status, 0);
	await chmod(join(first.extensionDir, "service-worker.js"), 0o600);
	const host = join(releaseB, "native-host.mjs");
	await writeFile(host, `${await readFile(host, "utf8")}\n// new browser component\n`);
	status = JSON.parse(run(releaseB, "status").stdout);
	assert.equal(status.installed, false); assert.notEqual(status.componentDigest, first.componentDigest);
	assert.equal(run(releaseB, "install").status, 0);
	assert.deepEqual(await readFile(join(first.extensionDir, "service-worker.js")), firstBytes, "旧组件不能覆盖或删除");
	await writeFile(join(status.extensionDir, "service-worker.js"), "corrupt", { mode: 0o600 });
	assert.equal(JSON.parse(run(releaseB, "status").stdout).componentState, "invalid");
	assert.notEqual(run(releaseB, "install").status, 0, "拒绝修复可能在使用的组件");
	assert.equal(await readFile(join(status.extensionDir, "service-worker.js"), "utf8"), "corrupt");
	await writeFile(host, `${await readFile(host, "utf8")}\n// another component\n`);
	status = JSON.parse(run(releaseB, "status").stdout);
	const outside = join(workspace, "outside"); await mkdir(outside); await writeFile(join(outside, "sentinel"), "keep");
	await symlink(outside, dirname(status.extensionDir));
	assert.equal(JSON.parse(run(releaseB, "status").stdout).componentState, "invalid");
	assert.notEqual(run(releaseB, "install").status, 0);
	assert.equal(await readFile(join(outside, "sentinel"), "utf8"), "keep");
	await writeFile(host, `${await readFile(host, "utf8")}\n// lock contention\n`);
	status = JSON.parse(run(releaseB, "status").stdout);
	const lock = `${dirname(status.extensionDir)}.lock`; await mkdir(lock, { mode: 0o700 });
	assert.notEqual(run(releaseB, "install").status, 0);
	assert.equal((await lstat(lock)).isDirectory(), true, "不能窃取未知安装留下的 lock");
	const redirectedHome = join(workspace, "redirected-home");
	await mkdir(join(redirectedHome, "Library"), { recursive: true });
	await symlink(outside, join(redirectedHome, "Library", "Application Support"));
	assert.notEqual(run(releaseB, "install", redirectedHome).status, 0);
	await assert.rejects(lstat(join(outside, "rotom")), { code: "ENOENT" }, "不能通过 symlink 父目录创建文件");
	const oversized = join(releaseB, "chrome-extension", "oversized.js");
	await writeFile(oversized, Buffer.alloc(2 * 1024 * 1024 + 1));
	assert.notEqual(run(releaseB, "status").status, 0, "component input must be bounded before reading");
	await rm(oversized);
	await rm(join(releaseB, "native-host.mjs")); await symlink(join(root, "native-host.mjs"), join(releaseB, "native-host.mjs"));
	assert.notEqual(run(releaseB, "status").status, 0, "source symlinks must be rejected");
});
