// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/baseten.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const BASETEN_MODELS: ChatModelCatalog<typeof values, "baseten"> =
	flattenChatModelCatalog("baseten", values);

export const BASETEN_IMAGE_MODELS: ImageModelCatalog<typeof values, "baseten"> =
	flattenImageModelCatalog("baseten", values);
