// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fireworks.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const FIREWORKS_MODELS: ChatModelCatalog<typeof values, "fireworks"> =
	flattenChatModelCatalog("fireworks", values);

export const FIREWORKS_IMAGE_MODELS: ImageModelCatalog<typeof values, "fireworks"> =
	flattenImageModelCatalog("fireworks", values);
