// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/google.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const GOOGLE_MODELS: ChatModelCatalog<typeof values, "google"> =
	flattenChatModelCatalog("google", values);

export const GOOGLE_IMAGE_MODELS: ImageModelCatalog<typeof values, "google"> =
	flattenImageModelCatalog("google", values);
