// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kimi-coding.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const KIMI_CODING_MODELS: ChatModelCatalog<typeof values, "kimi-coding"> =
	flattenChatModelCatalog("kimi-coding", values);

export const KIMI_CODING_IMAGE_MODELS: ImageModelCatalog<typeof values, "kimi-coding"> =
	flattenImageModelCatalog("kimi-coding", values);
