// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/meta.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const META_MODELS: ChatModelCatalog<typeof values, "meta"> =
	flattenChatModelCatalog("meta", values);

export const META_IMAGE_MODELS: ImageModelCatalog<typeof values, "meta"> =
	flattenImageModelCatalog("meta", values);
