// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax-cn.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const MINIMAX_CN_MODELS: ChatModelCatalog<typeof values, "minimax-cn"> =
	flattenChatModelCatalog("minimax-cn", values);

export const MINIMAX_CN_IMAGE_MODELS: ImageModelCatalog<typeof values, "minimax-cn"> =
	flattenImageModelCatalog("minimax-cn", values);
