// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openrouter.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const OPENROUTER_MODELS: ChatModelCatalog<typeof values, "openrouter"> =
	flattenChatModelCatalog("openrouter", values);

export const OPENROUTER_IMAGE_MODELS: ImageModelCatalog<typeof values, "openrouter"> =
	flattenImageModelCatalog("openrouter", values);
