// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/opencode-go.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const OPENCODE_GO_MODELS: ChatModelCatalog<typeof values, "opencode-go"> =
	flattenChatModelCatalog("opencode-go", values);

export const OPENCODE_GO_IMAGE_MODELS: ImageModelCatalog<typeof values, "opencode-go"> =
	flattenImageModelCatalog("opencode-go", values);
