// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/radius.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const RADIUS_MODELS: ChatModelCatalog<typeof values, "radius"> =
	flattenChatModelCatalog("radius", values);

export const RADIUS_IMAGE_MODELS: ImageModelCatalog<typeof values, "radius"> =
	flattenImageModelCatalog("radius", values);
