// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const XIAOMI_MODELS: ChatModelCatalog<typeof values, "xiaomi"> =
	flattenChatModelCatalog("xiaomi", values);

export const XIAOMI_IMAGE_MODELS: ImageModelCatalog<typeof values, "xiaomi"> =
	flattenImageModelCatalog("xiaomi", values);
