// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const ZAI_MODELS: ChatModelCatalog<typeof values, "zai"> =
	flattenChatModelCatalog("zai", values);

export const ZAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "zai"> =
	flattenImageModelCatalog("zai", values);
